### PR TITLE
Qubit tags

### PR DESCRIPTION
**Pull request by JakeRowsell89**
Added QTracker and Deliver tags to tag library

### CODE REVIEW

**Comment by oliverwoodings** [comment]
You need to pull master and rebase your branch off it

This looks really good - i'll go through the tags individually separately. Could you add exit feedback as well?

**Comment by JakeRowsell89** [comment]
Hey, sorry I meant to add the library tags to the V3 branch not master

**Comment by JakeRowsell89** [comment]
@oliverwoodings regarding the exit feedback, we do intend to add this but we may need to come up with a bit more interface as it's a little less plug-and-play than qtracker/deliver

**Comment by oliverwoodings** [comment]
So the plan is to leave the UI in the configurator, but instead of it automatically going into Opentag it will just output the JSON config. This can then be copy pasted into a JavaScript variable in Opentag, that can then be consumed by the library tag.

**Comment by JakeRowsell89** [comment]
That sounds good,  if I can be involved in that let me know as I'd be happy to learn and assist!

**Comment by peterfronc** [comment]
Its a pastie way, temporarily its ok but at the end we want more wysiwyg/config centric.
Leave it for now, we dont have feature implemented yet and I need to book some time for it so only pastie option can be used at the moment.

Those two libs are perfect for two other solutions (2 pasties less).

**Pull request closed without merging**
