### PR TITLE
update webgains UV tag

### PR DESCRIPTION
**Pull request by marcroberts**

### CODE REVIEW

**Comment by swagatha-christie** [comment]
By analyzing the blame information on this pull request, we identified @peterfronc to be a potential reviewer

**Comment by peterfronc** [comment]
Updates in minutes.

**Comment by peterfronc** [comment]
Please adjust http://www.webgains.com/public/wp-content/themes/webgains/images/logo-square.jpg logo.

**Comment by peterfronc** [comment]
Btw. Updates are out and public,

**Pull request merged**
