### PR TITLE
added fits.me v2

### PR DESCRIPTION
**Pull request by rogy**
fits.me finishing up

removed changes to build location

Please enter the commit message for your changes. Lines starting

removed out of fitsme changes

### CODE REVIEW

**Comment by peterfronc** [comment]
Is this merged?

**Comment by rogy** [comment]
I do not believe so no.

**Comment by peterfronc** [comment]
Should it be? Can you check other pulls and tell which are to be merged in?

**Comment by peterfronc** [comment]
Looks ok, testing and merging.

**Comment by peterfronc** [comment]
Merged.

**Pull request merged**
