### PR TITLE
facebookconversionpixel original script (url instead ?)

### PR DESCRIPTION
**Pull request by kendrick-k**
Could you check it, it works like this, but should I use url: "connect.facebook.net/${url_locale}/fbps.js" instead ? But could you advice to handle _fbq.loaded condition : necessary ? It's handled by Opentag ?

### CODE REVIEW

**Comment by oliverwoodings** [comment]
Is this a duplicate of some of the code in https://github.com/QubitProducts/opentag-library-sdk/pull/54 that just got merged?

**Comment by peterfronc** [comment]
Kendrick, I am reviewing it today. There is few classes to test. The parameters are allowed in urls, but recommended if they are not used internally, if its for internal use (not exposed) its not worth using it.

**Comment by peterfronc** [comment]
In this case it looks good in the code.

**Comment by peterfronc** [comment]
Kendrick can you also close old pull requests that are included in the new one?

**Comment by kendrick-k** [comment]
see Bundle tag add #62

**Pull request closed without merging**
