### PR TITLE
facebook pixel event, googledoubleclick adtagimpressiontracker, outbrain amplify pixel, taboola pixelretargeting

### PR DESCRIPTION
**Pull request by mediafigaro**
hello, I've added : facebook pixel event, googledoubleclick adtagimpressiontracker, outbrain amplify pixel, taboola pixelretargeting. Doc links are into the code, tell me if ou would need some modifications for you to be able to integrate it. Best, Kendrick.

### CODE REVIEW

**Comment by peterfronc** [comment]
Hey Kendrick, I'll have a look and integrate it into our libraries repo asap.

**Comment by peterfronc** [comment]
For future reference: code doesn't have to obfuscated - we have process compressing at output.
Code looks ok - once I finish tests I'll merge it in.

**Comment by peterfronc** [comment]
Kendrick - all libraries are live. Cheers!

**Comment by mediafigaro** [comment]
Cool :)

**Pull request merged**
