### PR TITLE
SmartAdServer main script

### PR DESCRIPTION
**Pull request by kendrick-k**
Added SmartAdServer main script, for review.

### CODE REVIEW

**Comment by peterfronc** [comment]
Please use master branch for adding libraries (opentag-v3 is unstable branch).

**Comment by kendrick-k** [comment]
ok, by the way how do you handle document.write ?

**Comment by peterfronc** [comment]
document.write operations can be handled by our SDK or tags can let them do their normal runtime flow.
If has document write option enabled - SDK at runtime will try to protect load and page from damage and wrap write native functions to redirect intput to SDK controlled output  - we will simply stop write functions from writing to page and redirect to out buffer to handle operations later on.

Please check docs at:
https://opentag.qubitproducts.com/tagsdk/docs/template.html#!/api/qubit.opentag.BaseTag-cfg-usesDocumentWrite

**Comment by kendrick-k** [comment]
Nice, thanks. Don't you use Postscribe ?

**Comment by kendrick-k** [comment]
close : new pull request from master

**Comment by peterfronc** [comment]
Nah, we have our own old API doing the job.

**Comment by kendrick-k** [comment]
:)

**Comment by peterfronc** [comment]
:-)

**Pull request closed without merging**
