### PR TITLE
Adding Media iQ

### PR DESCRIPTION
**Pull request by robbyduffy**
Emre and team.

I didn't manage to get the SDK working - I got lost after cloning the repository. One guide says type some java line but in your vid you do something different.

Anyway I copied your format and created the files using the UI.

A couple of our clients use Opentag. Our pixel just collects the browsers appnexus id and sends some assigned u-variables to our server.

robert.dufton@mediaiqdigital.com

### CODE REVIEW

**Comment by peterfronc** [comment]
@robbyduffy can you tell what issues you deal with?
I will be able to help you.

**Comment by peterfronc** [comment]
There is also official guide pages you can look at: https://opentag.qubitproducts.com/tagsdk/docs/template.html#!/guide/running_library

**Comment by peterfronc** [comment]
To build and try your library you need to trigger:

`sh build.sh  libraries/mediaiq`

I have tried it now and it looks like you have syntax errors in your files - therefore library won't be loaded.

**Comment by robbyduffy** [comment]
Following the readme it says "Make your changes against the branch."

...I think I wanted to create a folder in /libraries here but that instruction isn't clear. I "mkdir mediaiq" in /libraries and 
"$ git commit -am "stuff" && git push"
 but get response:

Untracked files:
        opentag-library-sdk/
nothing added to commit but untracked files present

Meanwhile in this guide: https://opentag.qubitproducts.com/tagsdk/docs/template.html#!/guide/getting_started
It says to type
java -jar shared/bin/LibraryWizard.jar --wizard
and it responds:
Error: Unable to access jarfile shared/bin/LibraryWizard.jar

**Comment by robbyduffy** [comment]
I think the error was in line 3 of Tag.js

**Comment by peterfronc** [comment]
I think on your machine you may need to run `chmod +x shared/bin/LibraryWizard.jar` but its very strange and I've never seen such issue before. Make sure the file has no zero size (maybe filesystem error).

That command basically triggers basic java VM to run a wizard that will prepare library package directory and library file from a template (the `Tag.js`).  New library is a template copy from `shared/template/Tag.js` file.

If you choose to create new library manually - copy template and in copy of the template you need to adjust PACKAGE_NAME and TAG_NAME. Package name is a standard classpath same like in java (in this case it is `mediaiq.aiqcapturetag.v1`).
Classpath uniquely defines where the `Tag.js` file reside and in this case it should be in `libraries/mediaiq/aiqcapturetag/v1/` directory.
It is recommended that classpath is made from Library name, so, "aiqcapturetag" would be made from "AIQ Capture Tag".

General structure in the repository is: `libraries/<VENDOR_NAME>/<LIBRARY_PACKAGE>/<VERSION>/Tag.js`

In Your directory structure the vendor name is `mediaiq` and you have package named `aiqcapturetag`, you are missing version directory (`v1` in this case).
In the `Tag.js` you must fix the classpath from `mediaiq.v1.Tag` to one that corresponds to the directory structure you will have (`mediaiq.aiqcapturetag.v1.Tag`).

Wizard makes this simple and automated.

To fix your library, move `Tag.js` file to `mediaiq/aiqcapturetag/v1` then update `Tag.js` package name from `mediaiq.v1.Tag` to `mediaiq.aiqcapturetag.v1.Tag` and fix the syntax errors.

Lemme know if you need more assistance.

**Comment by peterfronc** [comment]
There is still unescaped quotes at line 10.

**Comment by robbyduffy** [comment]
I figured that's how that path worked. Please could you see if it works now? I don't think that I need to re-push somehow? I've never used Git before.

I needed to escape the Speech marks in the html. And put in all the parameters.

**Comment by robbyduffy** [comment]
@peterfronc Any more thoughts on this one?

**Comment by peterfronc** [comment]
Looks good, Ill have to test integrity on my side and by tomorrow Ill make the release of it.

**Comment by peterfronc** [comment]
If everything is fine.

**Comment by peterfronc** [comment]
Can you confirm the uid=UID is correct in your pixel image? Once I get it confirmed Ill add it to our library.

**Comment by robbyduffy** [comment]
This is correct - It is the macro syntax for appnexus to add its own value replacing $UID.

Thanks!

**Comment by peterfronc** [comment]
Ok, I am now getting it through merge and deployments, Ill drop here update once all is out.

**Comment by peterfronc** [comment]
screen shot 2017-08-31 at 12 14 49
This is how it will look like in the panel.

**Comment by peterfronc** [comment]
Merged.

**Comment by peterfronc** [comment]
Released.

**Comment by robbyduffy** [comment]
I think it's fine - $UID is on the reserved macro list here: https://wiki.appnexus.com/display/adnexusdocumentation/AppNexus+Macros

However that **segment_id)]** is wrong too - apologies. Can you change it?

**Comment by peterfronc** [comment]
Ive fixed that for you at master branch. Please go to opentag and re-test your library (create tag using it and make sure it does what it should). If necessary, create another pull request with updates.

**Pull request merged**
