### PR TITLE
description and token syntax corrected

### PR DESCRIPTION
**Pull request by robbyduffy**

### CODE REVIEW

**Comment by peterfronc** [comment]
Released

**Comment by robbyduffy** [comment]
appreciated - I see that ALL the tokens need values assigned. is there an option so be able to leave these empty?

**Comment by peterfronc** [comment]
If its optional value, you should set a default value (it should not be undefined or null). More details at: 

https://opentag.qubitproducts.com/tagsdk/docs/template.html#!/guide/defining_parameter

**Comment by peterfronc** [comment]
In general, parameters are expected to be set, if not tag will hold execution till their values are available. Note that it will happen with certain delay as it will still wait for them and after timeout it will use defaults. I would recommend revising the logic and answer few questions:

1) When all parameters will be available?
2) Where the values are coming from?

Maybe for this case its better to write script section constructing url (using switch or if's) and then calling "this.loadURL(...)" in script body. I think you may be better off with script body.

**Comment by peterfronc** [comment]
More on Tag API: https://opentag.qubitproducts.com/tagsdk/docs/template.html#!/api/qubit.opentag.BaseTag

**Pull request merged**
